# Generated by Django 5.0.1 on 2026-01-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="room_code",
            field=models.CharField(db_index=True, default="default", max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room_code", "created_at"],
                name="board_messa_room_co_e6de55_idx",
            ),
        ),
    ]
