# Generated by Django 5.0.1 on 2026-01-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_message_room_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(default="Unnamed Room", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_code", models.CharField(db_index=True, max_length=50)),
                ("session_key", models.CharField(max_length=100)),
                ("last_visit", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session_key", "room_code"],
                        name="board_roomv_session_3ddd2c_idx",
                    )
                ],
                "unique_together": {("room_code", "session_key")},
            },
        ),
    ]
